# File: .github/workflows/python.yml
name: Python package

on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # checkout the repo
    - name: Cloning repository
      uses: actions/checkout@master
    
    - name: Get current run metadata using curL
      run: curl -X GET "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs"
       
    - name: App Service Web App Build Action
      uses: qianz2/appservice-build@master
   
# Azure login
#     - name: Deploying web app to Azure
#       uses: azure/webapps-deploy@v1
#       with:
#         app-name: python-docs-hello-world
#         publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
